import { Code } from './codeType';
import { lczList } from './countryLocalization';
import json from './json.json';
import { getCode } from './getters';

export type Goverment =
	| 'Republic'
	| 'Absolute monarchy'
	| 'Constitutional monarchy'
	| 'Provisional';

export const govList: { [K in Code]: Goverment } = {
	af: 'Provisional',
	al: 'Republic',
	dz: 'Republic',
	ad: 'Constitutional monarchy',
	ao: 'Republic',
	ag: 'Constitutional monarchy',
	ar: 'Republic',
	am: 'Republic',
	au: 'Constitutional monarchy',
	at: 'Republic',
	az: 'Republic',
	bs: 'Constitutional monarchy',
	bh: 'Constitutional monarchy',
	bd: 'Republic',
	bb: 'Republic',
	by: 'Republic',
	be: 'Constitutional monarchy',
	bz: 'Constitutional monarchy',
	bj: 'Republic',
	bt: 'Constitutional monarchy',
	bo: 'Republic',
	ba: 'Republic',
	bw: 'Republic',
	br: 'Republic',
	bn: 'Absolute monarchy',
	bg: 'Republic',
	bf: 'Provisional',
	bi: 'Republic',
	kh: 'Constitutional monarchy',
	cm: 'Republic',
	ca: 'Constitutional monarchy',
	cv: 'Republic',
	cf: 'Republic',
	td: 'Provisional',
	cl: 'Republic',
	cn: 'Republic',
	co: 'Republic',
	km: 'Republic',
	cd: 'Republic',
	cg: 'Republic',
	cr: 'Republic',
	ci: 'Republic',
	hr: 'Republic',
	cu: 'Republic',
	cy: 'Republic',
	cz: 'Republic',
	dk: 'Constitutional monarchy',
	dj: 'Republic',
	dm: 'Republic',
	do: 'Republic',
	tl: 'Republic',
	ec: 'Republic',
	eg: 'Republic',
	sv: 'Republic',
	gq: 'Republic',
	er: 'Republic',
	ee: 'Republic',
	sz: 'Absolute monarchy',
	et: 'Republic',
	fj: 'Republic',
	fi: 'Republic',
	fr: 'Republic',
	ga: 'Republic',
	gm: 'Republic',
	ge: 'Republic',
	de: 'Republic',
	gh: 'Republic',
	gr: 'Republic',
	gd: 'Constitutional monarchy',
	gt: 'Republic',
	gn: 'Provisional',
	gw: 'Republic',
	gy: 'Republic',
	ht: 'Republic',
	hn: 'Republic',
	hu: 'Republic',
	is: 'Republic',
	in: 'Republic',
	id: 'Republic',
	ir: 'Republic',
	iq: 'Republic',
	ie: 'Republic',
	il: 'Republic',
	it: 'Republic',
	jm: 'Constitutional monarchy',
	jp: 'Constitutional monarchy',
	jo: 'Constitutional monarchy',
	kz: 'Republic',
	ke: 'Republic',
	ki: 'Republic',
	kw: 'Constitutional monarchy',
	kg: 'Republic',
	la: 'Republic',
	lv: 'Republic',
	lb: 'Republic',
	ls: 'Constitutional monarchy',
	lr: 'Republic',
	ly: 'Provisional',
	li: 'Constitutional monarchy',
	lt: 'Republic',
	lu: 'Constitutional monarchy',
	mg: 'Republic',
	mw: 'Republic',
	my: 'Constitutional monarchy',
	mv: 'Republic',
	ml: 'Provisional',
	mt: 'Republic',
	mh: 'Republic',
	mr: 'Republic',
	mu: 'Republic',
	mx: 'Republic',
	fm: 'Republic',
	md: 'Republic',
	mc: 'Constitutional monarchy',
	mn: 'Republic',
	me: 'Republic',
	ma: 'Constitutional monarchy',
	mz: 'Republic',
	mm: 'Provisional',
	na: 'Republic',
	nr: 'Republic',
	np: 'Republic',
	nl: 'Constitutional monarchy',
	nz: 'Constitutional monarchy',
	ni: 'Republic',
	ne: 'Republic',
	ng: 'Republic',
	kp: 'Republic',
	mk: 'Republic',
	no: 'Constitutional monarchy',
	om: 'Absolute monarchy',
	pk: 'Republic',
	pw: 'Republic',
	ps: 'Republic',
	pa: 'Republic',
	pg: 'Constitutional monarchy',
	py: 'Republic',
	pe: 'Republic',
	ph: 'Republic',
	pl: 'Republic',
	pt: 'Republic',
	qa: 'Constitutional monarchy',
	ro: 'Republic',
	ru: 'Republic',
	rw: 'Republic',
	kn: 'Constitutional monarchy',
	lc: 'Constitutional monarchy',
	vc: 'Constitutional monarchy',
	ws: 'Republic',
	sm: 'Republic',
	st: 'Republic',
	sa: 'Absolute monarchy',
	sn: 'Republic',
	rs: 'Republic',
	sc: 'Republic',
	sl: 'Republic',
	sg: 'Republic',
	sk: 'Republic',
	si: 'Republic',
	sb: 'Constitutional monarchy',
	so: 'Republic',
	za: 'Republic',
	kr: 'Republic',
	ss: 'Republic',
	es: 'Constitutional monarchy',
	lk: 'Republic',
	sd: 'Provisional',
	sr: 'Republic',
	se: 'Constitutional monarchy',
	ch: 'Republic',
	sy: 'Republic',
	tj: 'Republic',
	tz: 'Republic',
	th: 'Constitutional monarchy',
	tg: 'Republic',
	to: 'Constitutional monarchy',
	tt: 'Republic',
	tn: 'Republic',
	tr: 'Republic',
	tm: 'Republic',
	tv: 'Constitutional monarchy',
	ug: 'Republic',
	ua: 'Republic',
	ae: 'Constitutional monarchy',
	gb: 'Constitutional monarchy',
	us: 'Republic',
	uy: 'Republic',
	uz: 'Republic',
	vu: 'Republic',
	va: 'Absolute monarchy',
	ve: 'Republic',
	vn: 'Republic',
	ye: 'Provisional',
	zm: 'Republic',
	zw: 'Republic',
	xk: 'Republic',
	tw: 'Republic',
};

export function generateList() {
	const govList = {} as { [K in Code]: Goverment };
	for (const country of json) {
		if (getCode(country.Name) === undefined) {
			console.log(country.Name);
			continue;
		} else {
			const gov = country['Constitutional form'];
			govList[getCode(country.Name) as Code] = gov as Goverment;
		}
	}
	console.log(govList);
}
