import { Code } from './codeType';
import { lczList } from './countryLocalization';
import data from './data.json';
import { getCode } from './getters';

export type Religion =
	| 'Irreligion'
	| 'Christianity'
	| 'Islam'
	| 'Hinduism'
	| 'Buddhism'
	| 'Judaism'
	| 'Other'
	| 'Folk Religion';

export const relList: { [K in Code]: Religion } = {
	af: 'Islam',
	al: 'Islam',
	dz: 'Islam',
	ad: 'Christianity',
	ao: 'Christianity',
	ag: 'Christianity',
	ar: 'Christianity',
	am: 'Christianity',
	au: 'Christianity',
	at: 'Christianity',
	az: 'Islam',
	bs: 'Christianity',
	bh: 'Islam',
	bd: 'Islam',
	bb: 'Christianity',
	by: 'Christianity',
	be: 'Christianity',
	bz: 'Christianity',
	bj: 'Christianity',
	bt: 'Buddhism',
	bo: 'Christianity',
	ba: 'Christianity',
	bw: 'Christianity',
	br: 'Christianity',
	bn: 'Islam',
	bg: 'Christianity',
	bf: 'Islam',
	bi: 'Christianity',
	kh: 'Buddhism',
	cm: 'Christianity',
	ca: 'Christianity',
	cv: 'Christianity',
	cf: 'Christianity',
	td: 'Islam',
	cl: 'Christianity',
	cn: 'Irreligion',
	co: 'Christianity',
	km: 'Islam',
	cr: 'Christianity',
	hr: 'Christianity',
	cu: 'Christianity',
	cy: 'Christianity',
	cz: 'Irreligion',
	dk: 'Christianity',
	dj: 'Islam',
	dm: 'Christianity',
	do: 'Christianity',
	cd: 'Christianity',
	ec: 'Christianity',
	eg: 'Islam',
	sv: 'Christianity',
	gq: 'Christianity',
	er: 'Christianity',
	ee: 'Irreligion',
	sz: 'Christianity',
	et: 'Christianity',
	fj: 'Christianity',
	fi: 'Christianity',
	fr: 'Christianity',
	ga: 'Christianity',
	gm: 'Islam',
	ge: 'Christianity',
	de: 'Christianity',
	gh: 'Christianity',
	gr: 'Christianity',
	gd: 'Christianity',
	gt: 'Christianity',
	gn: 'Islam',
	gw: 'Islam',
	gy: 'Christianity',
	ht: 'Christianity',
	hn: 'Christianity',
	hu: 'Christianity',
	is: 'Christianity',
	in: 'Hinduism',
	id: 'Islam',
	ir: 'Islam',
	iq: 'Islam',
	ie: 'Christianity',
	il: 'Judaism',
	it: 'Christianity',
	ci: 'Christianity',
	jm: 'Christianity',
	jp: 'Irreligion',
	jo: 'Islam',
	kz: 'Islam',
	ke: 'Christianity',
	ki: 'Christianity',
	kw: 'Islam',
	kg: 'Islam',
	la: 'Buddhism',
	lv: 'Christianity',
	lb: 'Islam',
	ls: 'Christianity',
	lr: 'Christianity',
	ly: 'Islam',
	li: 'Christianity',
	lt: 'Christianity',
	lu: 'Christianity',
	mg: 'Christianity',
	mw: 'Christianity',
	my: 'Islam',
	mv: 'Islam',
	ml: 'Islam',
	mt: 'Christianity',
	mh: 'Christianity',
	mr: 'Islam',
	mu: 'Hinduism',
	mx: 'Christianity',
	fm: 'Christianity',
	md: 'Christianity',
	mc: 'Christianity',
	mn: 'Buddhism',
	me: 'Christianity',
	ma: 'Islam',
	mz: 'Christianity',
	mm: 'Buddhism',
	na: 'Christianity',
	nr: 'Christianity',
	np: 'Hinduism',
	nl: 'Christianity',
	nz: 'Christianity',
	ni: 'Christianity',
	ne: 'Islam',
	ng: 'Christianity',
	kp: 'Irreligion',
	no: 'Christianity',
	om: 'Islam',
	pk: 'Islam',
	pw: 'Christianity',
	ps: 'Islam',
	pa: 'Christianity',
	pg: 'Christianity',
	py: 'Christianity',
	pe: 'Christianity',
	ph: 'Christianity',
	pl: 'Christianity',
	pt: 'Christianity',
	qa: 'Islam',
	cg: 'Christianity',
	ro: 'Christianity',
	ru: 'Christianity',
	rw: 'Christianity',
	kn: 'Christianity',
	vc: 'Christianity',
	ws: 'Christianity',
	sm: 'Christianity',
	st: 'Christianity',
	sa: 'Islam',
	sn: 'Islam',
	rs: 'Christianity',
	sc: 'Christianity',
	sl: 'Islam',
	sg: 'Buddhism',
	sk: 'Christianity',
	si: 'Christianity',
	sb: 'Christianity',
	so: 'Islam',
	za: 'Christianity',
	kr: 'Irreligion',
	ss: 'Christianity',
	es: 'Christianity',
	lk: 'Buddhism',
	sd: 'Islam',
	sr: 'Christianity',
	se: 'Christianity',
	ch: 'Christianity',
	sy: 'Islam',
	tw: 'Folk Religion',
	tj: 'Islam',
	tz: 'Christianity',
	th: 'Buddhism',
	tl: 'Christianity',
	tg: 'Christianity',
	to: 'Christianity',
	tt: 'Christianity',
	tn: 'Islam',
	tr: 'Islam',
	tm: 'Islam',
	tv: 'Christianity',
	ug: 'Christianity',
	ua: 'Christianity',
	ae: 'Islam',
	gb: 'Christianity',
	us: 'Christianity',
	uy: 'Christianity',
	uz: 'Islam',
	vu: 'Christianity',
	va: 'Christianity',
	ve: 'Christianity',
	vn: 'Folk Religion',
	ye: 'Islam',
	zm: 'Christianity',
	zw: 'Christianity',
	lc: 'Christianity',
	mk: 'Christianity',
	xk: 'Islam',
};

// export function generateRelList() {
// 	const list: { [K in Code]: string } = {};
// 	for (const country of data) {
// 		const code = getCode(country.country);
// 		if (code !== undefined) {
// 			let religion: [string, number] = ['Christianity', country.chistians];
// 			if (country.muslims > religion[1]) religion = ['Islam', country.muslims];
// 			if (country.unaffiliated > religion[1])
// 				religion = ['Irreligion', country.unaffiliated];
// 			if (country.hindus > religion[1]) religion = ['Hinduism', country.hindus];
// 			if (country.buddhists > religion[1])
// 				religion = ['Buddhism', country.buddhists];
// 			if (country.jews > religion[1]) religion = ['Judaism', country.jews];
// 			if (country.other > religion[1]) religion = ['Other', country.other];
// 			if (country.folkReligions > religion[1])
// 				religion = ['Folk Religion', country.folkReligions];
// 			list[code] = religion[0];
// 			continue;
// 		}
// 	}
// 	list.lc = 'Christianity';
// 	list.mk = 'Christianity';
// 	list.xk = 'Islam';
// 	console.log(list);
// }
