import { Code } from './codeType';
import { Continent } from './countryContinents';
import { Color } from './countryFlagColors';
import { lczList } from './countryLocalization';
import { getBorders, getCoastal, getContinent, getFlagColors } from './getters';

export type Country = {
	name: string[];
	borders: Code[];
	borderCount: number;
	coastal: boolean;
	continent: Continent;
	flagColors: Color[];
	flagColorCount: number;
};

export function generateList() {
	const list = {} as any;
	for (const cd in lczList) {
		const code = cd as Code;
		list[code] = {
			name: lczList[code],
			borders: getBorders(code),
			borderCount: getBorders(code).length,
			coastal: getCoastal(code),
			continent: getContinent(code),
			flagColors: getFlagColors(code),
			flagColorCount: getFlagColors(code).length,
		};
	}
	console.log(list);
}

export const uniList: { [K in Code]: Country } = {
	ad: {
		name: ['Andorra'],
		borders: ['fr', 'es'],
		borderCount: 2,
		coastal: true,
		continent: 'Europe',
		flagColors: ['red', 'blue', 'yellow', 'white', 'saffron'],
		flagColorCount: 5,
	},
	ae: {
		name: ['United Arab Emirates', 'UAE'],
		borders: ['om', 'sa'],
		borderCount: 2,
		coastal: false,
		continent: 'Asia',
		flagColors: ['green', 'black', 'red', 'white'],
		flagColorCount: 4,
	},
	af: {
		name: ['Afghanistan'],
		borders: ['cn', 'ir', 'pk', 'tj', 'tm', 'uz'],
		borderCount: 6,
		coastal: true,
		continent: 'Asia',
		flagColors: ['green', 'black', 'red', 'white', 'saffron'],
		flagColorCount: 5,
	},
	ag: {
		name: ['Antigua and Barbuda'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'North America',
		flagColors: ['red', 'black', 'liblue', 'white', 'yellow'],
		flagColorCount: 5,
	},
	al: {
		name: ['Albania'],
		borders: ['gr', 'me', 'mk', 'xk'],
		borderCount: 4,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'black'],
		flagColorCount: 2,
	},
	am: {
		name: ['Armenia'],
		borders: ['az', 'ge', 'ir', 'tr'],
		borderCount: 4,
		coastal: true,
		continent: 'Asia',
		flagColors: ['red', 'saffron', 'blue'],
		flagColorCount: 3,
	},
	ao: {
		name: ['Angola'],
		borders: ['cg', 'cd', 'na', 'zm'],
		borderCount: 4,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'black', 'yellow'],
		flagColorCount: 3,
	},
	ar: {
		name: ['Argentina'],
		borders: ['bo', 'br', 'cl', 'py', 'uy'],
		borderCount: 5,
		coastal: false,
		continent: 'South America',
		flagColors: ['liblue', 'white', 'saffron'],
		flagColorCount: 3,
	},
	at: {
		name: ['Austria'],
		borders: ['cz', 'de', 'hu', 'it', 'li', 'sk', 'si', 'ch'],
		borderCount: 8,
		coastal: true,
		continent: 'Europe',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	au: {
		name: ['Australia'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['blue', 'white', 'red'],
		flagColorCount: 3,
	},
	az: {
		name: ['Azerbaijan'],
		borders: ['am', 'ge', 'ir', 'ru', 'tr'],
		borderCount: 5,
		coastal: true,
		continent: 'Asia',
		flagColors: ['green', 'liblue', 'red', 'white'],
		flagColorCount: 4,
	},
	ba: {
		name: ['Bosnia and Herzegovina'],
		borders: ['hr', 'me', 'rs'],
		borderCount: 3,
		coastal: false,
		continent: 'Europe',
		flagColors: ['blue', 'yellow', 'white'],
		flagColorCount: 3,
	},
	bb: {
		name: ['Barbados'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'North America',
		flagColors: ['blue', 'yellow', 'black'],
		flagColorCount: 3,
	},
	bd: {
		name: ['Bangladesh'],
		borders: ['in', 'mm'],
		borderCount: 2,
		coastal: false,
		continent: 'Asia',
		flagColors: ['green', 'red'],
		flagColorCount: 2,
	},
	be: {
		name: ['Belgium'],
		borders: ['fr', 'de', 'lu', 'nl'],
		borderCount: 4,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'yellow', 'black'],
		flagColorCount: 3,
	},
	bf: {
		name: ['Burkina Faso'],
		borders: ['bj', 'ci', 'gh', 'ml', 'ne', 'tg'],
		borderCount: 6,
		coastal: true,
		continent: 'Africa',
		flagColors: ['red', 'green', 'yellow'],
		flagColorCount: 3,
	},
	bg: {
		name: ['Bulgaria'],
		borders: ['gr', 'mk', 'ro', 'rs', 'tr'],
		borderCount: 5,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'green', 'white'],
		flagColorCount: 3,
	},
	bh: {
		name: ['Bahrain'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	bi: {
		name: ['Burundi'],
		borders: ['cd', 'rw', 'tz'],
		borderCount: 3,
		coastal: true,
		continent: 'Africa',
		flagColors: ['green', 'white', 'red'],
		flagColorCount: 3,
	},
	bj: {
		name: ['Benin'],
		borders: ['bf', 'ne', 'ng', 'tg'],
		borderCount: 4,
		coastal: false,
		continent: 'Africa',
		flagColors: ['green', 'red', 'yellow'],
		flagColorCount: 3,
	},
	bn: {
		name: ['Brunei', 'Brunei Darussalam'],
		borders: ['my'],
		borderCount: 1,
		coastal: false,
		continent: 'Asia',
		flagColors: ['yellow', 'white', 'black', 'red'],
		flagColorCount: 4,
	},
	bo: {
		name: ['Bolivia', 'Bolivia (Plurinational State of)'],
		borders: ['ar', 'br', 'cl', 'py', 'pe'],
		borderCount: 5,
		coastal: true,
		continent: 'South America',
		flagColors: ['red', 'yellow', 'green'],
		flagColorCount: 3,
	},
	br: {
		name: ['Brazil'],
		borders: ['ar', 'bo', 'co', 'fr', 'gy', 'py', 'pe', 'sr', 'uy', 've'],
		borderCount: 10,
		coastal: false,
		continent: 'South America',
		flagColors: ['green', 'yellow', 'blue', 'white'],
		flagColorCount: 4,
	},
	bs: {
		name: ['Bahamas'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'North America',
		flagColors: ['liblue', 'yellow', 'black'],
		flagColorCount: 3,
	},
	bt: {
		name: ['Bhutan'],
		borders: ['cn', 'in'],
		borderCount: 2,
		coastal: true,
		continent: 'Asia',
		flagColors: ['yellow', 'red', 'white', 'saffron'],
		flagColorCount: 4,
	},
	bw: {
		name: ['Botswana'],
		borders: ['na', 'za', 'zm', 'zw'],
		borderCount: 4,
		coastal: true,
		continent: 'Africa',
		flagColors: ['liblue', 'black', 'white'],
		flagColorCount: 3,
	},
	by: {
		name: ['Belarus'],
		borders: ['lv', 'lt', 'pl', 'ru', 'ua'],
		borderCount: 5,
		coastal: true,
		continent: 'Europe',
		flagColors: ['red', 'green', 'white'],
		flagColorCount: 3,
	},
	bz: {
		name: ['Belize'],
		borders: ['gt', 'mx'],
		borderCount: 2,
		coastal: false,
		continent: 'North America',
		flagColors: ['blue', 'white', 'red', 'green', 'black'],
		flagColorCount: 5,
	},
	ca: {
		name: ['Canada'],
		borders: ['us'],
		borderCount: 1,
		coastal: false,
		continent: 'North America',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	cd: {
		name: [
			'Democratic Republic of the Congo',
			'Democratic Republic of Congo',
			'Congo, Democratic Republic of the',
			'DRC',
			'Congo Kinshasa',
		],
		borders: ['ao', 'bi', 'cf', 'cg', 'rw', 'ss', 'tz', 'ug', 'zm'],
		borderCount: 9,
		coastal: false,
		continent: 'Africa',
		flagColors: ['liblue', 'red', 'yellow'],
		flagColorCount: 3,
	},
	cf: {
		name: ['Central African Republic', 'CAR', 'Central African Rep'],
		borders: ['cm', 'td', 'cg', 'cd', 'ss', 'sd'],
		borderCount: 6,
		coastal: true,
		continent: 'Africa',
		flagColors: ['yellow', 'green', 'white', 'blue', 'red'],
		flagColorCount: 5,
	},
	cg: {
		name: ['Congo', 'Congo Brazzaville', 'Republic of the Congo'],
		borders: ['ao', 'cm', 'cf', 'cd', 'ga'],
		borderCount: 5,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'yellow', 'green'],
		flagColorCount: 3,
	},
	ch: {
		name: ['Switzerland'],
		borders: ['at', 'fr', 'de', 'it', 'li'],
		borderCount: 5,
		coastal: true,
		continent: 'Europe',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	ci: {
		name: ["Côte d'Ivoire", 'Ivory Coast', 'Cote d Ivoire'],
		borders: ['bf', 'gh', 'gn', 'lr', 'ml'],
		borderCount: 5,
		coastal: false,
		continent: 'Africa',
		flagColors: ['saffron', 'green', 'white'],
		flagColorCount: 3,
	},
	cl: {
		name: ['Chile'],
		borders: ['ar', 'bo', 'pe'],
		borderCount: 3,
		coastal: false,
		continent: 'South America',
		flagColors: ['red', 'white', 'blue'],
		flagColorCount: 3,
	},
	cm: {
		name: ['Cameroon'],
		borders: ['cf', 'td', 'cg', 'gq', 'ga', 'ng'],
		borderCount: 6,
		coastal: false,
		continent: 'Africa',
		flagColors: ['yellow', 'green', 'red'],
		flagColorCount: 3,
	},
	cn: {
		name: ['China', "People's Republic of China", 'PRC'],
		borders: [
			'af',
			'bt',
			'in',
			'kz',
			'kp',
			'kg',
			'la',
			'mn',
			'mm',
			'np',
			'pk',
			'ru',
			'tj',
			'vn',
		],
		borderCount: 14,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'yellow'],
		flagColorCount: 2,
	},
	co: {
		name: ['Colombia'],
		borders: ['br', 'ec', 'pa', 'pe', 've'],
		borderCount: 5,
		coastal: false,
		continent: 'South America',
		flagColors: ['yellow', 'red', 'blue'],
		flagColorCount: 3,
	},
	cr: {
		name: ['Costa Rica'],
		borders: ['ni', 'pa'],
		borderCount: 2,
		coastal: false,
		continent: 'North America',
		flagColors: ['red', 'blue', 'white'],
		flagColorCount: 3,
	},
	cu: {
		name: ['Cuba'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'North America',
		flagColors: ['blue', 'white', 'red'],
		flagColorCount: 3,
	},
	cv: {
		name: ['Cabo Verde', 'Cape Verde'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Africa',
		flagColors: ['blue', 'white', 'red', 'yellow'],
		flagColorCount: 4,
	},
	cy: {
		name: ['Cyprus'],
		borders: ['gb'],
		borderCount: 1,
		coastal: false,
		continent: 'Asia',
		flagColors: ['white', 'saffron', 'green'],
		flagColorCount: 3,
	},
	cz: {
		name: ['Czechia', 'Czech Republic', 'Czech Rep'],
		borders: ['at', 'de', 'pl', 'sk'],
		borderCount: 4,
		coastal: true,
		continent: 'Europe',
		flagColors: ['red', 'white', 'blue'],
		flagColorCount: 3,
	},
	de: {
		name: ['Germany'],
		borders: ['at', 'be', 'cz', 'dk', 'fr', 'lu', 'nl', 'pl', 'ch'],
		borderCount: 9,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'yellow', 'black'],
		flagColorCount: 3,
	},
	dj: {
		name: ['Djibouti'],
		borders: ['er', 'et', 'so'],
		borderCount: 3,
		coastal: false,
		continent: 'Africa',
		flagColors: ['green', 'liblue', 'white', 'saffron'],
		flagColorCount: 4,
	},
	dk: {
		name: ['Denmark'],
		borders: ['de'],
		borderCount: 1,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	dm: {
		name: ['Dominica'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'North America',
		flagColors: ['green', 'red', 'yellow', 'black', 'white'],
		flagColorCount: 5,
	},
	do: {
		name: ['Dominican Republic', 'Dominican Rep', 'Dominican'],
		borders: ['ht'],
		borderCount: 1,
		coastal: false,
		continent: 'North America',
		flagColors: ['red', 'blue', 'white', 'green'],
		flagColorCount: 4,
	},
	dz: {
		name: ['Algeria'],
		borders: ['ly', 'ml', 'mr', 'ma', 'ne', 'tn'],
		borderCount: 6,
		coastal: false,
		continent: 'Africa',
		flagColors: ['white', 'green', 'red'],
		flagColorCount: 3,
	},
	ec: {
		name: ['Ecuador'],
		borders: ['co', 'pe'],
		borderCount: 2,
		coastal: false,
		continent: 'South America',
		flagColors: ['yellow', 'red', 'blue', 'saffron', 'green', 'black'],
		flagColorCount: 6,
	},
	ee: {
		name: ['Estonia'],
		borders: ['lv', 'ru'],
		borderCount: 2,
		coastal: false,
		continent: 'Europe',
		flagColors: ['liblue', 'black', 'white'],
		flagColorCount: 3,
	},
	eg: {
		name: ['Egypt'],
		borders: ['il', 'ly', 'ps', 'sd'],
		borderCount: 4,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'black', 'white', 'yellow'],
		flagColorCount: 4,
	},
	er: {
		name: ['Eritrea'],
		borders: ['dj', 'et', 'sd'],
		borderCount: 3,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'green', 'liblue', 'yellow'],
		flagColorCount: 4,
	},
	es: {
		name: ['Spain'],
		borders: ['ad', 'fr', 'ma', 'pt', 'gb'],
		borderCount: 5,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'yellow', 'saffron', 'white'],
		flagColorCount: 4,
	},
	et: {
		name: ['Ethiopia'],
		borders: ['dj', 'er', 'ke', 'so', 'ss', 'sd'],
		borderCount: 6,
		coastal: true,
		continent: 'Africa',
		flagColors: ['red', 'green', 'yellow', 'liblue'],
		flagColorCount: 4,
	},
	fi: {
		name: ['Finland'],
		borders: ['no', 'ru', 'se'],
		borderCount: 3,
		coastal: false,
		continent: 'Europe',
		flagColors: ['white', 'blue'],
		flagColorCount: 2,
	},
	fj: {
		name: ['Fiji'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['liblue', 'red', 'white', 'blue'],
		flagColorCount: 4,
	},
	fm: {
		name: [
			'Micronesia',
			'Federated States of Micronesia',
			'Micronesia (Federated States of)',
		],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['liblue', 'white'],
		flagColorCount: 2,
	},
	fr: {
		name: ['France'],
		borders: ['ad', 'be', 'br', 'de', 'it', 'lu', 'mc', 'nl', 'es', 'sr', 'ch'],
		borderCount: 11,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'blue', 'white'],
		flagColorCount: 3,
	},
	ga: {
		name: ['Gabon'],
		borders: ['cm', 'cg', 'gq'],
		borderCount: 3,
		coastal: false,
		continent: 'Africa',
		flagColors: ['yellow', 'green', 'liblue'],
		flagColorCount: 3,
	},
	gb: {
		name: [
			'United Kingdom',
			'United Kingdom of Great Britain and Northern Ireland',
			'UK',
		],
		borders: ['ie', 'es', 'cy'],
		borderCount: 3,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'white', 'blue'],
		flagColorCount: 3,
	},
	gd: {
		name: ['Grenada'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'North America',
		flagColors: ['red', 'yellow', 'green'],
		flagColorCount: 3,
	},
	ge: {
		name: ['Georgia'],
		borders: ['am', 'az', 'ru', 'tr'],
		borderCount: 4,
		coastal: false,
		continent: 'Asia',
		flagColors: ['white', 'red'],
		flagColorCount: 2,
	},
	gh: {
		name: ['Ghana'],
		borders: ['bf', 'ci', 'tg'],
		borderCount: 3,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'green', 'yellow', 'black'],
		flagColorCount: 4,
	},
	gm: {
		name: ['Gambia'],
		borders: ['sn'],
		borderCount: 1,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'green', 'blue', 'white'],
		flagColorCount: 4,
	},
	gn: {
		name: ['Guinea'],
		borders: ['ci', 'gw', 'lr', 'ml', 'sn', 'sl'],
		borderCount: 6,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'yellow', 'green'],
		flagColorCount: 3,
	},
	gq: {
		name: ['Equatorial Guinea'],
		borders: ['cm', 'ga'],
		borderCount: 2,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'green', 'white', 'liblue'],
		flagColorCount: 4,
	},
	gr: {
		name: ['Greece'],
		borders: ['al', 'bg', 'mk', 'tr'],
		borderCount: 4,
		coastal: false,
		continent: 'Europe',
		flagColors: ['blue', 'white'],
		flagColorCount: 2,
	},
	gt: {
		name: ['Guatemala'],
		borders: ['bz', 'sv', 'hn', 'mx'],
		borderCount: 4,
		coastal: false,
		continent: 'North America',
		flagColors: ['liblue', 'white', 'saffron', 'green'],
		flagColorCount: 4,
	},
	gw: {
		name: ['Guinea-Bissau'],
		borders: ['gn', 'sn'],
		borderCount: 2,
		coastal: false,
		continent: 'Africa',
		flagColors: ['yellow', 'green', 'red', 'black'],
		flagColorCount: 4,
	},
	gy: {
		name: ['Guyana'],
		borders: ['br', 'sr', 've'],
		borderCount: 3,
		coastal: false,
		continent: 'South America',
		flagColors: ['green', 'red', 'yellow', 'white', 'black'],
		flagColorCount: 5,
	},
	hn: {
		name: ['Honduras'],
		borders: ['sv', 'gt', 'ni'],
		borderCount: 3,
		coastal: false,
		continent: 'North America',
		flagColors: ['liblue', 'white'],
		flagColorCount: 2,
	},
	hr: {
		name: ['Croatia'],
		borders: ['ba', 'hu', 'me', 'rs', 'si'],
		borderCount: 5,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'blue', 'white', 'liblue'],
		flagColorCount: 4,
	},
	ht: {
		name: ['Haiti'],
		borders: ['do'],
		borderCount: 1,
		coastal: false,
		continent: 'North America',
		flagColors: ['blue', 'red', 'white', 'green'],
		flagColorCount: 4,
	},
	hu: {
		name: ['Hungary'],
		borders: ['at', 'hr', 'ro', 'rs', 'sk', 'si', 'ua'],
		borderCount: 7,
		coastal: true,
		continent: 'Europe',
		flagColors: ['red', 'green', 'white'],
		flagColorCount: 3,
	},
	id: {
		name: ['Indonesia'],
		borders: ['my', 'pg', 'tl'],
		borderCount: 3,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	ie: {
		name: ['Ireland'],
		borders: ['gb'],
		borderCount: 1,
		coastal: false,
		continent: 'Europe',
		flagColors: ['saffron', 'green', 'white'],
		flagColorCount: 3,
	},
	il: {
		name: ['Israel'],
		borders: ['eg', 'jo', 'lb', 'ps', 'sy'],
		borderCount: 5,
		coastal: false,
		continent: 'Asia',
		flagColors: ['white', 'liblue'],
		flagColorCount: 2,
	},
	in: {
		name: ['India'],
		borders: ['bd', 'bt', 'cn', 'mm', 'np', 'pk'],
		borderCount: 6,
		coastal: false,
		continent: 'Asia',
		flagColors: ['saffron', 'green', 'white', 'blue'],
		flagColorCount: 4,
	},
	iq: {
		name: ['Iraq'],
		borders: ['ir', 'jo', 'kw', 'sa', 'sy', 'tr'],
		borderCount: 6,
		coastal: false,
		continent: 'Asia',
		flagColors: ['white', 'black', 'red', 'green'],
		flagColorCount: 4,
	},
	ir: {
		name: ['Iran', 'Islamic Republic of Iran', 'Iran (Islamic Republic of)'],
		borders: ['af', 'am', 'az', 'iq', 'pk', 'tr', 'tm'],
		borderCount: 7,
		coastal: false,
		continent: 'Asia',
		flagColors: ['white', 'red', 'green'],
		flagColorCount: 3,
	},
	is: {
		name: ['Iceland'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Europe',
		flagColors: ['blue', 'red', 'white'],
		flagColorCount: 3,
	},
	it: {
		name: ['Italy'],
		borders: ['at', 'fr', 'sm', 'si', 'ch', 'va'],
		borderCount: 6,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'green', 'white'],
		flagColorCount: 3,
	},
	jm: {
		name: ['Jamaica'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'North America',
		flagColors: ['yellow', 'green', 'black'],
		flagColorCount: 3,
	},
	jo: {
		name: ['Jordan'],
		borders: ['iq', 'il', 'ps', 'sa', 'sy'],
		borderCount: 5,
		coastal: false,
		continent: 'Asia',
		flagColors: ['green', 'black', 'red', 'white'],
		flagColorCount: 4,
	},
	jp: {
		name: ['Japan'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Asia',
		flagColors: ['white', 'red'],
		flagColorCount: 2,
	},
	ke: {
		name: ['Kenya'],
		borders: ['et', 'so', 'ss', 'tz', 'ug'],
		borderCount: 5,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'black', 'green', 'white'],
		flagColorCount: 4,
	},
	kg: {
		name: ['Kyrgyzstan'],
		borders: ['cn', 'kz', 'tj', 'uz'],
		borderCount: 4,
		coastal: true,
		continent: 'Asia',
		flagColors: ['red', 'yellow'],
		flagColorCount: 2,
	},
	kh: {
		name: ['Cambodia'],
		borders: ['la', 'th', 'vn'],
		borderCount: 3,
		coastal: false,
		continent: 'Asia',
		flagColors: ['blue', 'red', 'white', 'black'],
		flagColorCount: 4,
	},
	ki: {
		name: ['Kiribati'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['red', 'blue', 'white', 'yellow'],
		flagColorCount: 4,
	},
	km: {
		name: ['Comoros'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Africa',
		flagColors: ['yellow', 'green', 'liblue', 'white', 'red'],
		flagColorCount: 5,
	},
	kn: {
		name: [
			'Saint Kitts and Nevis',
			'St Kitts and Nevis',
			'Saint Kitts',
			'St Kitts',
		],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'North America',
		flagColors: ['black', 'red', 'green', 'yellow', 'white'],
		flagColorCount: 5,
	},
	kp: {
		name: [
			'North Korea',
			"Korea (Democratic People's Republic of)",
			'DPRK',
			'NK',
		],
		borders: ['cn', 'kr', 'ru'],
		borderCount: 3,
		coastal: false,
		continent: 'Asia',
		flagColors: ['white', 'black', 'red', 'blue'],
		flagColorCount: 4,
	},
	kr: {
		name: ['South Korea', 'Korea, Republic of'],
		borders: ['kp'],
		borderCount: 1,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'blue', 'white'],
		flagColorCount: 3,
	},
	kw: {
		name: ['Kuwait'],
		borders: ['iq', 'sa'],
		borderCount: 2,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'green', 'white', 'black'],
		flagColorCount: 4,
	},
	kz: {
		name: ['Kazakhstan'],
		borders: ['cn', 'kg', 'ru', 'tm', 'uz'],
		borderCount: 5,
		coastal: true,
		continent: 'Asia',
		flagColors: ['liblue', 'yellow'],
		flagColorCount: 2,
	},
	la: {
		name: [
			'Laos',
			"Lao People's Democratic Republic",
			"Lao People's Democratic Rep",
		],
		borders: ['cn', 'kh', 'mm', 'th', 'vn'],
		borderCount: 5,
		coastal: true,
		continent: 'Asia',
		flagColors: ['red', 'blue', 'white'],
		flagColorCount: 3,
	},
	lb: {
		name: ['Lebanon'],
		borders: ['il', 'sy'],
		borderCount: 2,
		coastal: false,
		continent: 'Asia',
		flagColors: ['saffron', 'white', 'green'],
		flagColorCount: 3,
	},
	lc: {
		name: ['Saint Lucia', 'St Lucia'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'North America',
		flagColors: ['blue', 'yellow', 'black', 'white'],
		flagColorCount: 4,
	},
	li: {
		name: ['Liechtenstein'],
		borders: ['at', 'ch'],
		borderCount: 2,
		coastal: true,
		continent: 'Europe',
		flagColors: ['red', 'blue', 'yellow', 'black'],
		flagColorCount: 4,
	},
	lk: {
		name: ['Sri Lanka'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Asia',
		flagColors: ['yellow', 'red', 'saffron', 'green'],
		flagColorCount: 4,
	},
	lr: {
		name: ['Liberia'],
		borders: ['ci', 'gn', 'sl'],
		borderCount: 3,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'white', 'blue'],
		flagColorCount: 3,
	},
	ls: {
		name: ['Lesotho'],
		borders: ['za'],
		borderCount: 1,
		coastal: true,
		continent: 'Africa',
		flagColors: ['white', 'green', 'blue', 'black'],
		flagColorCount: 4,
	},
	lt: {
		name: ['Lithuania'],
		borders: ['by', 'lv', 'pl', 'ru'],
		borderCount: 4,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'yellow', 'green'],
		flagColorCount: 3,
	},
	lu: {
		name: ['Luxembourg', 'Luxemburg'],
		borders: ['be', 'de', 'fr'],
		borderCount: 3,
		coastal: true,
		continent: 'Europe',
		flagColors: ['red', 'liblue', 'white'],
		flagColorCount: 3,
	},
	lv: {
		name: ['Latvia'],
		borders: ['by', 'ee', 'lt', 'ru'],
		borderCount: 4,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	ly: {
		name: ['Libya'],
		borders: ['dz', 'td', 'eg', 'ne', 'sd', 'tn'],
		borderCount: 6,
		coastal: false,
		continent: 'Africa',
		flagColors: ['black', 'red', 'green', 'white'],
		flagColorCount: 4,
	},
	ma: {
		name: ['Morocco'],
		borders: ['dz', 'es', 'mr'],
		borderCount: 3,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'green'],
		flagColorCount: 2,
	},
	mc: {
		name: ['Monaco'],
		borders: ['fr'],
		borderCount: 1,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	md: {
		name: ['Moldova', 'Moldova, Republic of'],
		borders: ['ro', 'ua'],
		borderCount: 2,
		coastal: true,
		continent: 'Europe',
		flagColors: ['red', 'blue', 'yellow', 'black'],
		flagColorCount: 4,
	},
	me: {
		name: ['Montenegro'],
		borders: ['al', 'ba', 'hr', 'rs', 'xk'],
		borderCount: 5,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'saffron', 'green', 'liblue'],
		flagColorCount: 4,
	},
	mg: {
		name: ['Madagascar'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'green', 'white'],
		flagColorCount: 3,
	},
	mh: {
		name: ['Marshall Islands'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['blue', 'white', 'saffron'],
		flagColorCount: 3,
	},
	mk: {
		name: ['North Macedonia', 'Macedonia'],
		borders: ['al', 'bg', 'gr', 'rs', 'xk'],
		borderCount: 5,
		coastal: true,
		continent: 'Europe',
		flagColors: ['red', 'yellow'],
		flagColorCount: 2,
	},
	ml: {
		name: ['Mali'],
		borders: ['dz', 'bf', 'ci', 'gn', 'mr', 'ne', 'sn'],
		borderCount: 7,
		coastal: true,
		continent: 'Africa',
		flagColors: ['red', 'yellow', 'green'],
		flagColorCount: 3,
	},
	mm: {
		name: ['Myanmar', 'Burma'],
		borders: ['bd', 'cn', 'in', 'la', 'th'],
		borderCount: 5,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'blue', 'white'],
		flagColorCount: 3,
	},
	mn: {
		name: ['Mongolia'],
		borders: ['cn', 'ru'],
		borderCount: 2,
		coastal: true,
		continent: 'Asia',
		flagColors: ['red', 'liblue', 'yellow'],
		flagColorCount: 3,
	},
	mr: {
		name: ['Mauritania'],
		borders: ['dz', 'ml', 'sn', 'ma'],
		borderCount: 4,
		coastal: false,
		continent: 'Africa',
		flagColors: ['green', 'yellow'],
		flagColorCount: 2,
	},
	mt: {
		name: ['Malta'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	mu: {
		name: ['Mauritius'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'green', 'yellow', 'blue'],
		flagColorCount: 4,
	},
	mv: {
		name: ['Maldives'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'green', 'white'],
		flagColorCount: 3,
	},
	mw: {
		name: ['Malawi'],
		borders: ['mz', 'tz', 'zm'],
		borderCount: 3,
		coastal: true,
		continent: 'Africa',
		flagColors: ['red', 'green', 'black'],
		flagColorCount: 3,
	},
	mx: {
		name: ['Mexico'],
		borders: ['bz', 'gt', 'us'],
		borderCount: 3,
		coastal: false,
		continent: 'North America',
		flagColors: ['red', 'green', 'white', 'saffron'],
		flagColorCount: 4,
	},
	my: {
		name: ['Malaysia'],
		borders: ['bn', 'id', 'th'],
		borderCount: 3,
		coastal: false,
		continent: 'Asia',
		flagColors: ['white', 'red', 'blue', 'yellow'],
		flagColorCount: 4,
	},
	mz: {
		name: ['Mozambique'],
		borders: ['mw', 'sz', 'za', 'tz', 'zm', 'zw'],
		borderCount: 6,
		coastal: false,
		continent: 'Africa',
		flagColors: ['yellow', 'green', 'black', 'red', 'white'],
		flagColorCount: 5,
	},
	na: {
		name: ['Namibia'],
		borders: ['ao', 'bw', 'za', 'zm'],
		borderCount: 4,
		coastal: false,
		continent: 'Africa',
		flagColors: ['green', 'blue', 'red', 'white', 'yellow'],
		flagColorCount: 5,
	},
	ne: {
		name: ['Niger'],
		borders: ['dz', 'bj', 'bf', 'td', 'ly', 'ml', 'ng'],
		borderCount: 7,
		coastal: true,
		continent: 'Africa',
		flagColors: ['saffron', 'green', 'white'],
		flagColorCount: 3,
	},
	ng: {
		name: ['Nigeria'],
		borders: ['bj', 'cm', 'td', 'ne'],
		borderCount: 4,
		coastal: false,
		continent: 'Africa',
		flagColors: ['green', 'white'],
		flagColorCount: 2,
	},
	ni: {
		name: ['Nicaragua'],
		borders: ['cr', 'hn'],
		borderCount: 2,
		coastal: false,
		continent: 'North America',
		flagColors: ['liblue', 'white'],
		flagColorCount: 2,
	},
	nl: {
		name: ['Netherlands'],
		borders: ['be', 'de', 'fr'],
		borderCount: 3,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'blue', 'white'],
		flagColorCount: 3,
	},
	no: {
		name: ['Norway'],
		borders: ['fi', 'ru', 'se'],
		borderCount: 3,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'blue', 'white'],
		flagColorCount: 3,
	},
	np: {
		name: ['Nepal'],
		borders: ['cn', 'in'],
		borderCount: 2,
		coastal: true,
		continent: 'Asia',
		flagColors: ['red', 'blue', 'white'],
		flagColorCount: 3,
	},
	nr: {
		name: ['Nauru'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['blue', 'yellow', 'white'],
		flagColorCount: 3,
	},
	nz: {
		name: ['New Zealand'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['blue', 'red', 'white'],
		flagColorCount: 3,
	},
	om: {
		name: ['Oman'],
		borders: ['ae', 'sa', 'ye'],
		borderCount: 3,
		coastal: false,
		continent: 'Asia',
		flagColors: ['saffron', 'white', 'green'],
		flagColorCount: 3,
	},
	pa: {
		name: ['Panama'],
		borders: ['co', 'cr'],
		borderCount: 2,
		coastal: false,
		continent: 'North America',
		flagColors: ['white', 'red', 'liblue'],
		flagColorCount: 3,
	},
	pe: {
		name: ['Peru'],
		borders: ['bo', 'br', 'cl', 'co', 'ec'],
		borderCount: 5,
		coastal: false,
		continent: 'South America',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	pg: {
		name: ['Papua New Guinea'],
		borders: ['id'],
		borderCount: 1,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['black', 'red', 'yellow', 'white'],
		flagColorCount: 4,
	},
	ph: {
		name: ['Philippines'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'blue', 'white', 'yellow'],
		flagColorCount: 4,
	},
	pk: {
		name: ['Pakistan'],
		borders: ['af', 'cn', 'in', 'ir'],
		borderCount: 4,
		coastal: false,
		continent: 'Asia',
		flagColors: ['green', 'white'],
		flagColorCount: 2,
	},
	pl: {
		name: ['Poland'],
		borders: ['by', 'cz', 'de', 'lt', 'ru', 'sk', 'ua'],
		borderCount: 7,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	ps: {
		name: ['Palestine', 'Palestine, State of'],
		borders: ['eg', 'il', 'jo'],
		borderCount: 3,
		coastal: false,
		continent: 'Asia',
		flagColors: ['green', 'black', 'white', 'red'],
		flagColorCount: 4,
	},
	pt: {
		name: ['Portugal'],
		borders: ['es'],
		borderCount: 1,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'green', 'yellow', 'white'],
		flagColorCount: 4,
	},
	pw: {
		name: ['Palau'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['liblue', 'yellow'],
		flagColorCount: 2,
	},
	py: {
		name: ['Paraguay'],
		borders: ['ar', 'bo', 'br'],
		borderCount: 3,
		coastal: true,
		continent: 'South America',
		flagColors: ['red', 'blue', 'white'],
		flagColorCount: 3,
	},
	qa: {
		name: ['Qatar'],
		borders: ['sa'],
		borderCount: 1,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	ro: {
		name: ['Romania'],
		borders: ['bg', 'hu', 'md', 'rs', 'ua'],
		borderCount: 5,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'yellow', 'blue'],
		flagColorCount: 3,
	},
	rs: {
		name: ['Serbia'],
		borders: ['ba', 'bg', 'hr', 'hu', 'me', 'mk', 'ro', 'xk'],
		borderCount: 8,
		coastal: true,
		continent: 'Europe',
		flagColors: ['red', 'white', 'blue', 'yellow'],
		flagColorCount: 4,
	},
	ru: {
		name: ['Russia', 'Russian Federation'],
		borders: [
			'az',
			'by',
			'cn',
			'ee',
			'fi',
			'ge',
			'kz',
			'kp',
			'lv',
			'lt',
			'mn',
			'no',
			'pl',
			'ua',
		],
		borderCount: 14,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'blue', 'white'],
		flagColorCount: 3,
	},
	rw: {
		name: ['Rwanda'],
		borders: ['bi', 'cd', 'tz', 'ug'],
		borderCount: 4,
		coastal: true,
		continent: 'Africa',
		flagColors: ['liblue', 'yellow', 'green', 'saffron'],
		flagColorCount: 4,
	},
	sa: {
		name: ['Saudi Arabia'],
		borders: ['iq', 'jo', 'kw', 'om', 'qa', 'ae', 'ye'],
		borderCount: 7,
		coastal: false,
		continent: 'Asia',
		flagColors: ['green', 'white'],
		flagColorCount: 2,
	},
	sb: {
		name: ['Solomon Islands'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['green', 'liblue', 'yellow', 'white'],
		flagColorCount: 4,
	},
	sc: {
		name: ['Seychelles'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'yellow', 'green', 'blue', 'white'],
		flagColorCount: 5,
	},
	sd: {
		name: ['Sudan'],
		borders: ['cf', 'td', 'eg', 'et', 'er', 'ly', 'ss'],
		borderCount: 7,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'black', 'white', 'green'],
		flagColorCount: 4,
	},
	se: {
		name: ['Sweden'],
		borders: ['fi', 'no'],
		borderCount: 2,
		coastal: false,
		continent: 'Europe',
		flagColors: ['blue', 'yellow'],
		flagColorCount: 2,
	},
	sg: {
		name: ['Singapore'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Asia',
		flagColors: ['white', 'red'],
		flagColorCount: 2,
	},
	si: {
		name: ['Slovenia'],
		borders: ['at', 'hr', 'hu', 'it'],
		borderCount: 4,
		coastal: false,
		continent: 'Europe',
		flagColors: ['red', 'liblue', 'white'],
		flagColorCount: 3,
	},
	sk: {
		name: ['Slovakia'],
		borders: ['at', 'cz', 'hu', 'pl', 'ua'],
		borderCount: 5,
		coastal: true,
		continent: 'Europe',
		flagColors: ['red', 'white', 'blue'],
		flagColorCount: 3,
	},
	sl: {
		name: ['Sierra Leone'],
		borders: ['gn', 'lr'],
		borderCount: 2,
		coastal: false,
		continent: 'Africa',
		flagColors: ['green', 'liblue', 'white'],
		flagColorCount: 3,
	},
	sm: {
		name: ['San Marino'],
		borders: ['it'],
		borderCount: 1,
		coastal: true,
		continent: 'Europe',
		flagColors: ['white', 'liblue', 'green', 'yellow'],
		flagColorCount: 4,
	},
	sn: {
		name: ['Senegal'],
		borders: ['gm', 'gn', 'gw', 'ml', 'mr'],
		borderCount: 5,
		coastal: false,
		continent: 'Africa',
		flagColors: ['green', 'red', 'yellow'],
		flagColorCount: 3,
	},
	so: {
		name: ['Somalia'],
		borders: ['dj', 'et', 'ke'],
		borderCount: 3,
		coastal: false,
		continent: 'Africa',
		flagColors: ['liblue', 'white'],
		flagColorCount: 2,
	},
	sr: {
		name: ['Suriname'],
		borders: ['br', 'fr', 'gy'],
		borderCount: 3,
		coastal: false,
		continent: 'South America',
		flagColors: ['green', 'red', 'white', 'yellow'],
		flagColorCount: 4,
	},
	ss: {
		name: ['South Sudan'],
		borders: ['cf', 'cd', 'et', 'ke', 'sd', 'ug'],
		borderCount: 6,
		coastal: true,
		continent: 'Africa',
		flagColors: ['green', 'black', 'blue', 'red', 'white', 'yellow'],
		flagColorCount: 6,
	},
	st: {
		name: ['São Tomé and Príncipe', 'Sao Tome and Principe', 'Sao Tome'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Africa',
		flagColors: ['green', 'yellow', 'red', 'black'],
		flagColorCount: 4,
	},
	sv: {
		name: ['El Salvador'],
		borders: ['gt', 'hn'],
		borderCount: 2,
		coastal: false,
		continent: 'North America',
		flagColors: ['blue', 'white'],
		flagColorCount: 2,
	},
	sy: {
		name: ['Syria', 'Syrian Arab Republic', 'Syrian Arab Rep', 'Syrian Arab'],
		borders: ['iq', 'il', 'jo', 'lb', 'tr'],
		borderCount: 5,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'black', 'white', 'green'],
		flagColorCount: 4,
	},
	sz: {
		name: ['Eswatini', 'Swaziland'],
		borders: ['mz', 'za'],
		borderCount: 2,
		coastal: true,
		continent: 'Africa',
		flagColors: ['liblue', 'red', 'yellow', 'black', 'white', 'saffron'],
		flagColorCount: 6,
	},
	td: {
		name: ['Chad'],
		borders: ['cm', 'cf', 'ly', 'ne', 'ng', 'sd'],
		borderCount: 6,
		coastal: true,
		continent: 'Africa',
		flagColors: ['red', 'yellow', 'blue'],
		flagColorCount: 3,
	},
	tg: {
		name: ['Togo'],
		borders: ['bj', 'bf', 'gh'],
		borderCount: 3,
		coastal: false,
		continent: 'Africa',
		flagColors: ['green', 'yellow', 'red', 'white'],
		flagColorCount: 4,
	},
	th: {
		name: ['Thailand'],
		borders: ['kh', 'la', 'my', 'mm'],
		borderCount: 4,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'blue', 'white'],
		flagColorCount: 3,
	},
	tj: {
		name: ['Tajikistan'],
		borders: ['af', 'cn', 'kg', 'uz'],
		borderCount: 4,
		coastal: true,
		continent: 'Asia',
		flagColors: ['white', 'red', 'green', 'yellow'],
		flagColorCount: 4,
	},
	tl: {
		name: ['Timor-Leste', 'East Timor'],
		borders: ['id'],
		borderCount: 1,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'black', 'yellow', 'white'],
		flagColorCount: 4,
	},
	tm: {
		name: ['Turkmenistan'],
		borders: ['af', 'ir', 'kz', 'uz'],
		borderCount: 4,
		coastal: true,
		continent: 'Asia',
		flagColors: ['green', 'red', 'saffron', 'white'],
		flagColorCount: 4,
	},
	tn: {
		name: ['Tunisia'],
		borders: ['dz', 'ly'],
		borderCount: 2,
		coastal: false,
		continent: 'Africa',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	to: {
		name: ['Tonga'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	tr: {
		name: ['Turkey'],
		borders: ['am', 'az', 'bg', 'ge', 'gr', 'ir', 'iq', 'sy'],
		borderCount: 8,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'white'],
		flagColorCount: 2,
	},
	tt: {
		name: ['Trinidad and Tobago'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'North America',
		flagColors: ['red', 'black', 'white'],
		flagColorCount: 3,
	},
	tv: {
		name: ['Tuvalu'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['liblue', 'red', 'white', 'blue', 'yellow'],
		flagColorCount: 5,
	},
	tw: {
		name: ['Taiwan', 'Taiwan, Province of China'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'blue', 'white'],
		flagColorCount: 3,
	},
	tz: {
		name: ['Tanzania', 'Tanzania, United Republic of'],
		borders: ['bi', 'cd', 'ke', 'mw', 'mz', 'rw', 'ug', 'zm'],
		borderCount: 8,
		coastal: false,
		continent: 'Africa',
		flagColors: ['green', 'liblue', 'black', 'yellow'],
		flagColorCount: 4,
	},
	ua: {
		name: ['Ukraine'],
		borders: ['by', 'hu', 'md', 'pl', 'ro', 'ru', 'sk'],
		borderCount: 7,
		coastal: false,
		continent: 'Europe',
		flagColors: ['yellow', 'liblue'],
		flagColorCount: 2,
	},
	ug: {
		name: ['Uganda'],
		borders: ['cd', 'ke', 'rw', 'ss', 'tz'],
		borderCount: 5,
		coastal: true,
		continent: 'Africa',
		flagColors: ['yellow', 'red', 'black', 'white'],
		flagColorCount: 4,
	},
	us: {
		name: ['United States of America', 'United States', 'USA'],
		borders: ['ca', 'mx'],
		borderCount: 2,
		coastal: false,
		continent: 'North America',
		flagColors: ['red', 'white', 'blue'],
		flagColorCount: 3,
	},
	uy: {
		name: ['Uruguay'],
		borders: ['ar', 'br'],
		borderCount: 2,
		coastal: false,
		continent: 'South America',
		flagColors: ['white', 'blue', 'yellow', 'black'],
		flagColorCount: 4,
	},
	uz: {
		name: ['Uzbekistan'],
		borders: ['af', 'kz', 'kg', 'tj', 'tm'],
		borderCount: 5,
		coastal: true,
		continent: 'Asia',
		flagColors: ['white', 'green', 'liblue', 'red'],
		flagColorCount: 4,
	},
	va: {
		name: ['Vatican', 'Holy See', 'Vatican City'],
		borders: ['it'],
		borderCount: 1,
		coastal: true,
		continent: 'Europe',
		flagColors: ['yellow', 'white', 'saffron'],
		flagColorCount: 3,
	},
	vc: {
		name: [
			'Saint Vincent and the Grenadines',
			'Saint Vincent',
			'St Vincent and the Grenadines',
			'St Vincent',
		],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'North America',
		flagColors: ['yellow', 'green', 'liblue'],
		flagColorCount: 3,
	},
	ve: {
		name: ['Venezuela', 'Venezuela (Bolivarian Republic of)'],
		borders: ['br', 'co', 'gy'],
		borderCount: 3,
		coastal: false,
		continent: 'South America',
		flagColors: ['red', 'yellow', 'blue', 'white'],
		flagColorCount: 4,
	},
	vn: {
		name: ['Vietnam', 'Viet Nam'],
		borders: ['kh', 'cn', 'la'],
		borderCount: 3,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'yellow'],
		flagColorCount: 2,
	},
	vu: {
		name: ['Vanuatu'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['red', 'green', 'black', 'yellow'],
		flagColorCount: 4,
	},
	ws: {
		name: ['Samoa'],
		borders: [],
		borderCount: 0,
		coastal: false,
		continent: 'Oceania',
		flagColors: ['red', 'blue'],
		flagColorCount: 2,
	},
	xk: {
		name: ['Kosovo'],
		borders: ['al', 'me', 'mk', 'rs'],
		borderCount: 4,
		coastal: true,
		continent: 'Europe',
		flagColors: ['blue', 'yellow', 'white'],
		flagColorCount: 3,
	},
	ye: {
		name: ['Yemen'],
		borders: ['om', 'sa'],
		borderCount: 2,
		coastal: false,
		continent: 'Asia',
		flagColors: ['red', 'black', 'white'],
		flagColorCount: 3,
	},
	za: {
		name: ['South Africa'],
		borders: ['bw', 'ls', 'mz', 'na', 'sz', 'zw'],
		borderCount: 6,
		coastal: false,
		continent: 'Africa',
		flagColors: ['green', 'red', 'blue', 'white', 'black', 'yellow'],
		flagColorCount: 6,
	},
	zm: {
		name: ['Zambia'],
		borders: ['ao', 'bw', 'cd', 'mw', 'mz', 'na', 'tz', 'zw'],
		borderCount: 8,
		coastal: true,
		continent: 'Africa',
		flagColors: ['green', 'saffron', 'red', 'black'],
		flagColorCount: 4,
	},
	zw: {
		name: ['Zimbabwe'],
		borders: ['bw', 'mz', 'za', 'zm'],
		borderCount: 4,
		coastal: true,
		continent: 'Africa',
		flagColors: ['yellow', 'green', 'red', 'black', 'white'],
		flagColorCount: 5,
	},
};
